import { chromium } from 'playwright';
import fs from 'fs';
const CHROME='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const frag = fs.readFileSync('dist/override-standalone.html','utf8');
const doc = '<!doctype html><html><head><meta charset="utf-8"></head><body>'+frag+'</body></html>';
fs.writeFileSync('dist/_verify.html', doc);
const b=await chromium.launch({executablePath:CHROME,headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--disable-dev-shm-usage']});
const p=await b.newPage({viewport:{width:1280,height:720}});
const errs=[];
p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto('file://'+process.cwd()+'/dist/_verify.html',{waitUntil:'domcontentloaded',timeout:30000});
await p.waitForFunction(()=>{const b=document.getElementById('start-btn');return b&&!b.disabled;},{timeout:40000});
await p.click('#start-btn');
await p.waitForFunction(()=>window.__GAME__&&window.__GAME__.running,{timeout:15000});
await p.waitForTimeout(1500);
const st=await p.evaluate(()=>({running:window.__GAME__.running,fallback:window.__GAME__.input.fallbackLook,draws:window.__GAME__.renderer.info.render.calls,enemies:window.__GAME__.enemies.enemies.length}));
await p.screenshot({path:'tools/shots/standalone-verify.png'});
await b.close();
console.log('STATE',JSON.stringify(st));
console.log(errs.length? 'ERRORS:\n'+errs.slice(0,10).join('\n') : 'no console/page errors');
